# Generated by Django 4.2.7 on 2024-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='activated',
            field=models.BooleanField(null=True),
        ),
    ]
