# Generated by Django 4.2.7 on 2023-12-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lawyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='license_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='rating',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
